# Generated by Django 6.0.3 on 2026-04-02 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_completo",
                    models.CharField(max_length=200, verbose_name="Nome Completo"),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Matrícula"
                    ),
                ),
                ("funcao", models.CharField(max_length=100, verbose_name="Função")),
                ("setor", models.CharField(max_length=100, verbose_name="Setor")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ca", models.CharField(max_length=50, unique=True, verbose_name="CA")),
                ("descricao", models.TextField(verbose_name="Descrição Completa")),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="epi_fotos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RegistroEPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_retirada",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Retirada"
                    ),
                ),
                (
                    "quantidade",
                    models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="epi.colaborador",
                    ),
                ),
                (
                    "epi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="epi.epi",
                    ),
                ),
            ],
        ),
    ]
