# Generated by Django 6.0 on 2026-05-01 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("epi", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="colaboradores_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="colaborador",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="epi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="epis_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="epi",
            name="quantidade_em_estoque",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade em Estoque"
            ),
        ),
        migrations.AddField(
            model_name="epi",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="epi",
            name="validade_ca",
            field=models.DateField(
                blank=True, null=True, verbose_name="Validade do CA"
            ),
        ),
        migrations.AddField(
            model_name="registroepi",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registros_criados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="DevolucaoEPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_devolucao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Devolução"
                    ),
                ),
                (
                    "quantidade_devolvida",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantidade Devolvida"
                    ),
                ),
                ("observacao", models.TextField(blank=True, verbose_name="Observação")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="devolucoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registro",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devolucao",
                        to="epi.registroepi",
                    ),
                ),
            ],
        ),
    ]
